sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nsalfos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nsalfos/docker-react npm run test -- --coverage
