name: WorkLoad Healthcheck
on: 
  workflow_dispatch:

jobs:
  workload-healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Install workload HC helm chart
        run: cat ./docker-compose.yml
      - name: folder
        run: cat ./src/App.test.js
